name: Hide OHF Badge
slug: hide_ohf_badge
version: "1.0.0"
description: One-click add-on to hide Home Assistant splash badge
startup: once
boot: false
schema: {}
options: {}
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
image: ghcr.io/home-assistant/{arch}-base:latest
icon: icon.svg
